name:                Planner
version:             0.2.0
github:              "neco8/Planner"
license:             BSD3
author:              "neco8"
maintainer:          "shogibeshow@gmail.com"
copyright:           "2022 neco8"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/neco8/Planner#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- replace-megaparsec
- containers
- microlens
- microlens-th
- text
- vector
- optparse-declarative
- barbies
- barbies-th
- scientific
- Chart
- Chart-diagrams
- time
- recursion-schemes
- safe

library:
  source-dirs: src

executables:
  planner:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Planner

tests:
  Planner-tasty:
    main: Tasty.hs
    source-dirs: test-tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Planner
    - tasty
    - hspec-megaparsec
    - QuickCheck
    - doctest